export type { IconProps } from './types'
export * from './icons-navigation'
export * from './icons-toolbar'
export * from './icons-people-calendar'
export * from './icons-documents-reports'
export * from './icons-workspace-views'
export * from './icons-help-settings'
export * from './icons-sidebar'
export * from './icons-assistant'
